"""transfer_partners confidence_score and source_note

Revision ID: 2316a640831d
Revises: 9057f566edd3
Create Date: 2026-07-01 22:05:59.735356

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2316a640831d"
down_revision: Union[str, Sequence[str], None] = "9057f566edd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transfer_partners", sa.Column("confidence_score", sa.Float(), nullable=False))
    op.add_column("transfer_partners", sa.Column("source_note", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transfer_partners", "source_note")
    op.drop_column("transfer_partners", "confidence_score")
    # ### end Alembic commands ###
