"""reward_rules cap mechanics + local embedding dim 384

Revision ID: 9057f566edd3
Revises: aba69a56faf0
Create Date: 2026-07-01 17:04:46.833562

"""

from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9057f566edd3"
down_revision: Union[str, Sequence[str], None] = "aba69a56faf0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_chunks",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
        existing_nullable=True,
    )
    # add_column() with a bare Enum type does not create the Postgres type first (unlike
    # create_table(), which fires a before_create event for it) - create it explicitly.
    cap_basis_enum = sa.Enum("SPEND", "REWARD_UNITS", name="capbasis")
    cap_basis_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "reward_rules",
        sa.Column("cap_basis", cap_basis_enum, nullable=True),
    )
    op.add_column("reward_rules", sa.Column("excess_reward_rate", sa.Float(), nullable=True))
    op.add_column("reward_rules", sa.Column("exclusion_note", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reward_rules", "exclusion_note")
    op.drop_column("reward_rules", "excess_reward_rate")
    op.drop_column("reward_rules", "cap_basis")
    op.alter_column(
        "document_chunks",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
    # op.drop_column() does not emit DROP TYPE for the capbasis enum (same Alembic gap as
    # the initial migration) - drop it explicitly.
    op.execute("DROP TYPE IF EXISTS capbasis")
