"""initial schema: card_documents, document_chunks, reward_rules, transfer_partners, user_profiles, recommendation_logs

Revision ID: aba69a56faf0
Revises:
Create Date: 2026-07-01 16:31:26.756804

"""

from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aba69a56faf0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector must exist before any table can declare a VECTOR column (Section 10.1).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "card_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_name", sa.String(length=255), nullable=False),
        sa.Column("issuer", sa.String(length=255), nullable=False),
        sa.Column("document_type", sa.String(length=50), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_card_documents_card_name"), "card_documents", ["card_name"], unique=False
    )
    op.create_table(
        "recommendation_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("intent", sa.String(length=100), nullable=True),
        sa.Column("retrieved_chunk_ids", sa.JSON(), nullable=False),
        sa.Column("tool_calls", sa.JSON(), nullable=True),
        sa.Column("final_answer", sa.JSON(), nullable=True),
        sa.Column("confidence", sa.String(length=50), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("token_usage", sa.JSON(), nullable=True),
        sa.Column("feedback", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_recommendation_logs_user_created",
        "recommendation_logs",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "user_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("cards_owned", sa.JSON(), nullable=False),
        sa.Column("preferences", sa.JSON(), nullable=False),
        sa.Column("conversation_summary", sa.Text(), nullable=True),
        sa.Column("monthly_spend_pattern", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_profiles_user_id"), "user_profiles", ["user_id"], unique=True)
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("card_name", sa.String(length=255), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["card_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_chunks_card_name"), "document_chunks", ["card_name"], unique=False
    )
    op.create_index(
        op.f("ix_document_chunks_document_id"), "document_chunks", ["document_id"], unique=False
    )
    op.create_index(
        "ix_document_chunks_embedding_hnsw",
        "document_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_table(
        "reward_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("source_chunk_id", sa.Integer(), nullable=True),
        sa.Column("card_name", sa.String(length=255), nullable=False),
        sa.Column("spend_category", sa.String(length=100), nullable=False),
        sa.Column("reward_rate", sa.Float(), nullable=False),
        sa.Column(
            "reward_unit", sa.Enum("POINTS", "MILES", "CASHBACK", name="rewardunit"), nullable=False
        ),
        sa.Column("cap_type", sa.Enum("MONTHLY", "ANNUAL", name="captype"), nullable=True),
        sa.Column("cap_value", sa.Float(), nullable=True),
        sa.Column("exclusion_flag", sa.Boolean(), nullable=False),
        sa.Column("milestone_flag", sa.Boolean(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "PENDING_REVIEW", "SUPERSEDED", name="rewardrulestatus"),
            nullable=False,
        ),
        sa.Column("conflict_flag", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["card_documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_chunk_id"], ["document_chunks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_reward_rules_card_category",
        "reward_rules",
        ["card_name", "spend_category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reward_rules_document_id"), "reward_rules", ["document_id"], unique=False
    )
    op.create_table(
        "transfer_partners",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("source_chunk_id", sa.Integer(), nullable=True),
        sa.Column("card_name", sa.String(length=255), nullable=False),
        sa.Column("partner_name", sa.String(length=255), nullable=False),
        sa.Column("transfer_ratio_from", sa.Float(), nullable=False),
        sa.Column("transfer_ratio_to", sa.Float(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["card_documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_chunk_id"], ["document_chunks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transfer_partners_card_name"), "transfer_partners", ["card_name"], unique=False
    )
    op.create_index(
        op.f("ix_transfer_partners_document_id"), "transfer_partners", ["document_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transfer_partners_document_id"), table_name="transfer_partners")
    op.drop_index(op.f("ix_transfer_partners_card_name"), table_name="transfer_partners")
    op.drop_table("transfer_partners")
    op.drop_index(op.f("ix_reward_rules_document_id"), table_name="reward_rules")
    op.drop_index("ix_reward_rules_card_category", table_name="reward_rules")
    op.drop_table("reward_rules")
    # op.drop_table() does not emit DROP TYPE for the Postgres enums backing reward_rules'
    # Enum columns (a known Alembic autogenerate gap) - drop them explicitly.
    op.execute("DROP TYPE IF EXISTS rewardrulestatus")
    op.execute("DROP TYPE IF EXISTS captype")
    op.execute("DROP TYPE IF EXISTS rewardunit")
    op.drop_index(
        "ix_document_chunks_embedding_hnsw",
        table_name="document_chunks",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(op.f("ix_document_chunks_document_id"), table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_card_name"), table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index(op.f("ix_user_profiles_user_id"), table_name="user_profiles")
    op.drop_table("user_profiles")
    op.drop_index("ix_recommendation_logs_user_created", table_name="recommendation_logs")
    op.drop_table("recommendation_logs")
    op.drop_index(op.f("ix_card_documents_card_name"), table_name="card_documents")
    op.drop_table("card_documents")
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
